"""Created Roles[1]

Revision ID: 06cdfccb3089
Revises: 26e696146141
Create Date: 2023-05-16 11:32:01.301159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06cdfccb3089'
down_revision = '26e696146141'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Roles',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID'),
    schema='People'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Roles', schema='People')
    # ### end Alembic commands ###
