"""Initial

Revision ID: 0704cb23a10b
Revises: 
Create Date: 2023-05-08 23:03:32.780461

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0704cb23a10b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Departments',
                    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('Name', sa.VARCHAR(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('ID'),
                    sa.UniqueConstraint('ID'),
                    schema='Peoples'
                    )
    op.create_table('Users',
                    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('Name', sa.VARCHAR(length=50), nullable=False),
                    sa.Column('Surname', sa.VARCHAR(length=50), nullable=False),
                    sa.Column('TelegramChatID', sa.BIGINT(), nullable=False),
                    sa.Column('IsActive', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('ID'),
                    sa.UniqueConstraint('ID'),
                    schema='Peoples'
                    )
    op.create_table('Workers',
                    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('Name', sa.VARCHAR(length=50), nullable=False),
                    sa.Column('Surname', sa.VARCHAR(length=50), nullable=False),
                    sa.Column('TelegramChatID', sa.BIGINT(), nullable=False),
                    sa.Column('IsActive', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('ID'),
                    sa.UniqueConstraint('ID'),
                    schema='Peoples'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Workers', schema='Peoples')
    op.drop_table('Users', schema='Peoples')
    op.drop_table('Departments', schema='Peoples')
    # ### end Alembic commands ###
