"""Deleted dick length

Revision ID: 1760cfec04cd
Revises: 8085bf09461b
Create Date: 2023-05-09 13:19:22.577918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1760cfec04cd'
down_revision = '8085bf09461b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Workers', 'DickLength', schema='Peoples')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workers', sa.Column('DickLength', sa.SMALLINT(), autoincrement=False, nullable=True), schema='Peoples')
    # ### end Alembic commands ###
