"""Deleted Workers and all links to them, created Roles

Revision ID: 26e696146141
Revises: 25dd7a767c86
Create Date: 2023-05-15 13:33:22.084354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '26e696146141'
down_revision = '25dd7a767c86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Workers', schema='People')
    op.add_column('Users', sa.Column('PhoneNumber', sa.Integer(), nullable=False), schema='People')
    op.add_column('Users', sa.Column('RoleID', sa.Integer(), nullable=False), schema='People')
    op.add_column('Tickets', sa.Column('User_ID', sa.Integer(), nullable=False), schema='Tickets')
    op.create_foreign_key(None, 'Tickets', 'Users', ['User_ID'], ['ID'], source_schema='Tickets',
                          referent_schema='People')
    op.create_foreign_key(None, 'Tickets', 'Users', ['Responsible_ID'], ['ID'], source_schema='Tickets',
                          referent_schema='People')
    op.drop_column('Tickets', 'Worker_ID', schema='Tickets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tickets', sa.Column('Worker_ID', sa.INTEGER(), autoincrement=False, nullable=False),
                  schema='Tickets')
    op.drop_constraint(None, 'Tickets', schema='Tickets', type_='foreignkey')
    op.drop_constraint(None, 'Tickets', schema='Tickets', type_='foreignkey')
    op.create_foreign_key('FK__Tickets__Respons__2E70E1FD', 'Tickets', 'Workers', ['Responsible_ID'], ['ID'],
                          source_schema='Tickets', referent_schema='People')
    op.create_foreign_key('FK__Tickets__Worker___30592A6F', 'Tickets', 'Workers', ['Worker_ID'], ['ID'],
                          source_schema='Tickets', referent_schema='People')
    op.drop_column('Tickets', 'User_ID', schema='Tickets')
    op.drop_column('Users', 'RoleID', schema='People')
    op.drop_column('Users', 'PhoneNumber', schema='People')
    op.create_table('Workers',
                    sa.Column('ID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True,
                              nullable=False),
                    sa.Column('Name', sa.VARCHAR(length=50, collation='Cyrillic_General_CI_AS'), autoincrement=False,
                              nullable=False),
                    sa.Column('Surname', sa.VARCHAR(length=50, collation='Cyrillic_General_CI_AS'), autoincrement=False,
                              nullable=False),
                    sa.Column('TelegramChatID', sa.BIGINT(), autoincrement=False, nullable=False),
                    sa.Column('IsActive', mssql.BIT(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('ID', name='PK__Workers__3214EC279548E806'),
                    schema='People'
                    )
    # ### end Alembic commands ###
