"""Added dick length

Revision ID: 8085bf09461b
Revises: 6322fca83286
Create Date: 2023-05-09 12:57:59.402483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8085bf09461b'
down_revision = '6322fca83286'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workers', sa.Column('DickLength', sa.SMALLINT(), nullable=True), schema='Peoples')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Workers', 'DickLength', schema='Peoples')
    # ### end Alembic commands ###
