"""Added commands and permissions for them

Revision ID: a2b28876b5ab
Revises: 11a4a30ddff3
Create Date: 2023-05-18 22:22:12.558160

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a2b28876b5ab'
down_revision = '11a4a30ddff3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Commands',
                    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('Name', sa.VARCHAR(length=50), nullable=False),
                    sa.Column('Command', sa.VARCHAR(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('ID'),
                    sa.UniqueConstraint('ID')
                    )
    op.create_table('CommandPermissions',
                    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('Command_ID', sa.Integer(), nullable=False),
                    sa.Column('Role_ID', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['Command_ID'], ['Commands.ID'], ),
                    sa.ForeignKeyConstraint(['Role_ID'], ['People.Roles.ID'], ),
                    sa.PrimaryKeyConstraint('ID'),
                    sa.UniqueConstraint('ID')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CommandPermissions')
    op.drop_table('Commands')
    # ### end Alembic commands ###
