"""Refactored Processedmessages: added Text and MediaID instead of MessageData

Revision ID: faefe4cab12d
Revises: a2b28876b5ab
Create Date: 2023-05-23 15:07:46.897079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faefe4cab12d'
down_revision = 'a2b28876b5ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProcessedMessages', sa.Column('Text', sa.VARCHAR(), nullable=True), schema='Appeals')
    op.add_column('ProcessedMessages', sa.Column('MediaID', sa.Integer(), nullable=True), schema='Appeals')
    op.drop_column('ProcessedMessages', 'MessageData', schema='Appeals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProcessedMessages', sa.Column('MessageData', sa.VARCHAR(collation='Cyrillic_General_CI_AS'), autoincrement=False, nullable=True), schema='Appeals')
    op.drop_column('ProcessedMessages', 'MediaID', schema='Appeals')
    op.drop_column('ProcessedMessages', 'Text', schema='Appeals')
    # ### end Alembic commands ###
